/*
 * Copyright (c) 2022-2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * This file is autogenerated.  Do not edit.
 */

#include "th500_soc_regops_allowlist.h"

struct allowlist th500_perfmon_alist[67] = {
	{0x00000000, true},
	{0x00000004, true},
	{0x00000008, true},
	{0x0000000c, true},
	{0x00000010, true},
	{0x00000014, true},
	{0x00000020, true},
	{0x00000024, true},
	{0x00000028, true},
	{0x0000002c, true},
	{0x00000030, true},
	{0x00000034, true},
	{0x00000040, true},
	{0x00000044, true},
	{0x00000048, true},
	{0x0000004c, true},
	{0x00000050, true},
	{0x00000054, true},
	{0x00000058, true},
	{0x0000005c, true},
	{0x00000060, true},
	{0x00000064, true},
	{0x00000068, true},
	{0x0000006c, true},
	{0x00000070, true},
	{0x00000074, true},
	{0x00000078, true},
	{0x0000007c, true},
	{0x00000080, true},
	{0x00000084, true},
	{0x00000088, true},
	{0x0000008c, true},
	{0x00000090, true},
	{0x00000098, true},
	{0x0000009c, true},
	{0x000000a0, true},
	{0x000000a4, true},
	{0x000000a8, true},
	{0x000000ac, true},
	{0x000000b0, true},
	{0x000000b4, true},
	{0x000000b8, true},
	{0x000000bc, true},
	{0x000000c0, true},
	{0x000000c4, true},
	{0x000000c8, true},
	{0x000000cc, true},
	{0x000000d0, true},
	{0x000000d4, true},
	{0x000000d8, true},
	{0x000000dc, true},
	{0x000000e0, true},
	{0x000000e4, true},
	{0x000000e8, true},
	{0x000000ec, true},
	{0x000000f8, true},
	{0x000000fc, true},
	{0x00000100, true},
	{0x00000108, true},
	{0x00000110, true},
	{0x00000114, true},
	{0x00000118, true},
	{0x0000011c, true},
	{0x00000120, true},
	{0x00000124, true},
	{0x00000128, true},
	{0x00000130, true},
};

struct allowlist th500_pma_res_cmd_slice_rtr_alist[44] = {
	{0x00000800, false},
	{0x00000a00, false},
	{0x00000a10, false},
	{0x00000a20, false},
	{0x00000a24, false},
	{0x00000a38, false},
	{0x00000a3c, false},
	{0x00000a40, false},
	{0x00000a44, false},
	{0x00000a48, false},
	{0x00000a4c, false},
	{0x00000a50, false},
	{0x00000a54, false},
	{0x00000a58, false},
	{0x00000a5c, false},
	{0x00000ae4, false},
	{0x00000af0, false},
	{0x00000af4, false},
	{0x00000afc, false},
	{0x00000b00, false},
	{0x00000b04, false},
	{0x00000b08, false},
	{0x00000b0c, false},
	{0x00000b10, false},
	{0x00000b14, false},
	{0x00000b18, false},
	{0x00000b1c, false},
	{0x00000b20, false},
	{0x00000b24, false},
	{0x00000b28, false},
	{0x00000b2c, false},
	{0x00000b30, false},
	{0x00000b34, false},
	{0x00000b38, false},
	{0x00000b3c, false},
	{0x00000b40, false},
	{0x00000b44, false},
	{0x00000b48, false},
	{0x00000b4c, false},
	{0x00000b50, false},
	{0x00000b54, false},
	{0x00000b58, false},
	{0x00000b5c, false},
	{0x0000075c, false},
};

struct allowlist th500_pma_res_pma_alist[1] = {
	{0x00000800, true},
};

struct allowlist th500_rtr_alist[5] = {
	{0x0000005c, false},
	{0x00000044, false},
	{0x00000050, false},
	{0x00000048, false},
	{0x0000004c, false},
};

struct allowlist th500_nvlrx_alist[5] = {
	{0x00003340, false},
	{0x00000d00, false},
	{0x00000d04, false},
	{0x00001d00, false},
	{0x00001d04, false},
};

struct allowlist th500_nvltx_alist[3] = {
	{0x00000180, false},
	{0x00001500, false},
	{0x00001504, false},
};

struct allowlist th500_nvlctrl_alist[2] = {
	{0x00000804, false},
	{0x00000808, false},
};

struct allowlist th500_smmu_alist[1] = {
	{0x00005000, false},
};

struct allowlist th500_c2c_alist[52] = {
	{0x00000028, false},
	{0x00001028, false},
	{0x000020ec, false},
	{0x000020f0, false},
	{0x000020f4, false},
	{0x000020f8, false},
	{0x000020fc, false},
	{0x000030ec, false},
	{0x000030f0, false},
	{0x000030f4, false},
	{0x000030f8, false},
	{0x000030fc, false},
	{0x000040ec, false},
	{0x000040f0, false},
	{0x000040f4, false},
	{0x000040f8, false},
	{0x000040fc, false},
	{0x000050ec, false},
	{0x000050f0, false},
	{0x000050f4, false},
	{0x000050f8, false},
	{0x000050fc, false},
	{0x000060ec, false},
	{0x000060f0, false},
	{0x000060f4, false},
	{0x000060f8, false},
	{0x000060fc, false},
	{0x000070ec, false},
	{0x000070f0, false},
	{0x000070f4, false},
	{0x000070f8, false},
	{0x000070fc, false},
	{0x000080ec, false},
	{0x000080f0, false},
	{0x000080f4, false},
	{0x000080f8, false},
	{0x000080fc, false},
	{0x000090ec, false},
	{0x000090f0, false},
	{0x000090f4, false},
	{0x000090f8, false},
	{0x000090fc, false},
	{0x0000a0ec, false},
	{0x0000a0f0, false},
	{0x0000a0f4, false},
	{0x0000a0f8, false},
	{0x0000a0fc, false},
	{0x0000b0ec, false},
	{0x0000b0f0, false},
	{0x0000b0f4, false},
	{0x0000b0f8, false},
	{0x0000b0fc, false},
};

struct allowlist th500_pcie_alist[1] = {
	{0x00000470, true},
};

struct allowlist th500_mss_channel_alist[2] = {
	{0x00008914, false},
	{0x00008918, false},
};

struct allowlist th500_mcf_core_alist[2] = {
	{0x0000d604, false},
	{0x0000d600, false},
};

struct allowlist th500_mcf_clink_alist[3] = {
	{0x0000d610, false},
	{0x0000d614, false},
	{0x0000e430, false},
};

struct allowlist th500_mcf_c2c_alist[2] = {
	{0x0000d608, false},
	{0x0000d60c, false},
};

struct allowlist th500_mcf_ocu_alist[1] = {
	{0x0000d620, false},
};

struct allowlist th500_mcf_iobhx_alist[2] = {
	{0x0000d618, false},
	{0x0000d61c, false},
};

struct allowlist th500_mss_hub_alist[3] = {
	{0x00006f34, false},
	{0x00006f38, false},
	{0x00006f3c, false},
};

struct allowlist th500_cl2_alist[4] = {
	{0x00000550, false},
	{0x00000578, false},
	{0x00000750, false},
	{0x00000778, false},
};
