/*
 * Copyright (c) 2022-2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * This file is autogenerated.  Do not edit.
 */

#ifndef TH500_HWPM_REGOPS_ALLOWLIST_H
#define TH500_HWPM_REGOPS_ALLOWLIST_H

#include <tegra_hwpm.h>

extern struct allowlist th500_perfmon_alist[67];
extern struct allowlist th500_pma_res_cmd_slice_rtr_alist[44];
extern struct allowlist th500_pma_res_pma_alist[1];
extern struct allowlist th500_rtr_alist[5];
extern struct allowlist th500_nvlink_alist[0];
extern struct allowlist th500_smmu_alist[1];
extern struct allowlist th500_c2c_alist[52];
extern struct allowlist th500_pcie_alist[1];
extern struct allowlist th500_mss_channel_alist[2];
extern struct allowlist th500_mcf_core_alist[2];
extern struct allowlist th500_mcf_clink_alist[3];
extern struct allowlist th500_mcf_c2c_alist[2];
extern struct allowlist th500_mcf_soc_alist[2];
extern struct allowlist th500_soc_hub_alist[3];
extern struct allowlist th500_cl2_alist[4];

#endif /* TH500_HWPM_REGOPS_ALLOWLIST_H */
